export interface IndicatorDefinition {
  id: string;
  name: string;
  category: 'price' | 'moving_average' | 'rsi' | 'momentum' | 'volatility' | 'trend' | 'aroon' | 'macd_ppo' | 'volume';
  defaultPeriod: number;
  minPeriod: number;
  maxPeriod: number;
  comparatorHint: 'GT' | 'LT' | 'BOTH';
  thresholdRange: [number, number];
  description?: string;
  windowless?: boolean; // true if indicator doesn't use a configurable window
}

export const INDICATORS: Record<string, IndicatorDefinition> = {
  // ============================================================================
  // PRICE (1)
  // ============================================================================
  'Current Price': {
    id: 'Current Price',
    name: 'Current Price',
    category: 'price',
    defaultPeriod: 1,
    minPeriod: 1,
    maxPeriod: 1,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 1000],
    description: 'Current close price',
    windowless: true,
  },

  // ============================================================================
  // MOVING AVERAGES (8)
  // ============================================================================
  'Simple Moving Average': {
    id: 'Simple Moving Average',
    name: 'Simple Moving Average (SMA)',
    category: 'moving_average',
    defaultPeriod: 50,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Average price over N periods',
  },
  'Exponential Moving Average': {
    id: 'Exponential Moving Average',
    name: 'Exponential Moving Average (EMA)',
    category: 'moving_average',
    defaultPeriod: 50,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Exponentially weighted moving average',
  },
  'Hull Moving Average': {
    id: 'Hull Moving Average',
    name: 'Hull Moving Average',
    category: 'moving_average',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Weighted MA designed to reduce lag',
  },
  'Weighted Moving Average': {
    id: 'Weighted Moving Average',
    name: 'Weighted Moving Average (WMA)',
    category: 'moving_average',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Linearly weighted moving average',
  },
  'Wilder Moving Average': {
    id: 'Wilder Moving Average',
    name: 'Wilder Moving Average',
    category: 'moving_average',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Wilder smoothing (RMA)',
  },
  'DEMA': {
    id: 'DEMA',
    name: 'Double Exponential MA (DEMA)',
    category: 'moving_average',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Double exponential moving average',
  },
  'TEMA': {
    id: 'TEMA',
    name: 'Triple Exponential MA (TEMA)',
    category: 'moving_average',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Triple exponential moving average',
  },
  'KAMA': {
    id: 'KAMA',
    name: 'Kaufman Adaptive MA (KAMA)',
    category: 'moving_average',
    defaultPeriod: 10,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Adaptive moving average',
  },

  // ============================================================================
  // RSI & VARIANTS (5)
  // ============================================================================
  'RSI': {
    id: 'RSI',
    name: 'Relative Strength Index (Wilder)',
    category: 'rsi',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Wilder RSI (0-100)',
  },
  'RSI (SMA)': {
    id: 'RSI (SMA)',
    name: 'RSI using SMA smoothing',
    category: 'rsi',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'RSI with SMA smoothing',
  },
  'RSI (EMA)': {
    id: 'RSI (EMA)',
    name: 'RSI using EMA smoothing',
    category: 'rsi',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'RSI with EMA smoothing',
  },
  'Stochastic RSI': {
    id: 'Stochastic RSI',
    name: 'Stochastic RSI',
    category: 'rsi',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Stochastic applied to RSI',
  },
  'Laguerre RSI': {
    id: 'Laguerre RSI',
    name: 'Laguerre RSI',
    category: 'rsi',
    defaultPeriod: 4,
    minPeriod: 2,
    maxPeriod: 20,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Laguerre transform RSI',
  },

  // ============================================================================
  // MOMENTUM (9)
  // ============================================================================
  'Momentum (Weighted)': {
    id: 'Momentum (Weighted)',
    name: 'Momentum (13612W weighted)',
    category: 'momentum',
    defaultPeriod: 1,
    minPeriod: 1,
    maxPeriod: 1,
    comparatorHint: 'BOTH',
    thresholdRange: [-50, 50],
    description: '1-3-6-12 weighted momentum',
    windowless: true,
  },
  'Momentum (Unweighted)': {
    id: 'Momentum (Unweighted)',
    name: 'Momentum (13612U unweighted)',
    category: 'momentum',
    defaultPeriod: 1,
    minPeriod: 1,
    maxPeriod: 1,
    comparatorHint: 'BOTH',
    thresholdRange: [-50, 50],
    description: '1-3-6-12 unweighted momentum',
    windowless: true,
  },
  'Momentum (12-Month SMA)': {
    id: 'Momentum (12-Month SMA)',
    name: 'Momentum (12-Month SMA)',
    category: 'momentum',
    defaultPeriod: 12,
    minPeriod: 1,
    maxPeriod: 24,
    comparatorHint: 'BOTH',
    thresholdRange: [-50, 50],
    description: '12-month SMA momentum',
  },
  'Rate of Change': {
    id: 'Rate of Change',
    name: 'Rate of Change (ROC)',
    category: 'momentum',
    defaultPeriod: 12,
    minPeriod: 1,
    maxPeriod: 252,
    comparatorHint: 'BOTH',
    thresholdRange: [-50, 50],
    description: 'Percent price change',
  },
  'Williams %R': {
    id: 'Williams %R',
    name: 'Williams %R',
    category: 'momentum',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [-100, 0],
    description: 'Williams Percent Range',
  },
  'CCI': {
    id: 'CCI',
    name: 'Commodity Channel Index',
    category: 'momentum',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [-200, 200],
    description: 'Commodity Channel Index',
  },
  'Stochastic %K': {
    id: 'Stochastic %K',
    name: 'Stochastic %K',
    category: 'momentum',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Stochastic oscillator %K',
  },
  'Stochastic %D': {
    id: 'Stochastic %D',
    name: 'Stochastic %D',
    category: 'momentum',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Stochastic oscillator %D',
  },
  'ADX': {
    id: 'ADX',
    name: 'Average Directional Index',
    category: 'momentum',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'GT',
    thresholdRange: [0, 100],
    description: 'Trend strength indicator',
  },

  // ============================================================================
  // VOLATILITY (10)
  // ============================================================================
  'Standard Deviation': {
    id: 'Standard Deviation',
    name: 'Standard Deviation',
    category: 'volatility',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 252,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Standard deviation of returns',
  },
  'Standard Deviation of Price': {
    id: 'Standard Deviation of Price',
    name: 'Standard Deviation of Price',
    category: 'volatility',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 252,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Standard deviation of price',
  },
  'Max Drawdown': {
    id: 'Max Drawdown',
    name: 'Max Drawdown',
    category: 'volatility',
    defaultPeriod: 252,
    minPeriod: 20,
    maxPeriod: 1260,
    comparatorHint: 'LT',
    thresholdRange: [-100, 0],
    description: 'Maximum peak-to-trough decline',
  },
  'Drawdown': {
    id: 'Drawdown',
    name: 'Drawdown (current from ATH)',
    category: 'volatility',
    defaultPeriod: 252,
    minPeriod: 20,
    maxPeriod: 1260,
    comparatorHint: 'LT',
    thresholdRange: [-100, 0],
    description: 'Current drawdown from all-time high',
  },
  'Bollinger %B': {
    id: 'Bollinger %B',
    name: 'Bollinger %B',
    category: 'volatility',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 1],
    description: 'Price position within Bollinger Bands',
  },
  'Bollinger Bandwidth': {
    id: 'Bollinger Bandwidth',
    name: 'Bollinger Bandwidth',
    category: 'volatility',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 10],
    description: 'Width of Bollinger Bands',
  },
  'ATR': {
    id: 'ATR',
    name: 'Average True Range',
    category: 'volatility',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Average True Range',
  },
  'ATR %': {
    id: 'ATR %',
    name: 'ATR as percentage of price',
    category: 'volatility',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 20],
    description: 'ATR as percentage of close',
  },
  'Historical Volatility': {
    id: 'Historical Volatility',
    name: 'Historical Volatility',
    category: 'volatility',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 252,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Annualized historical volatility',
  },
  'Ulcer Index': {
    id: 'Ulcer Index',
    name: 'Ulcer Index',
    category: 'volatility',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'LT',
    thresholdRange: [0, 50],
    description: 'Downside volatility measure',
  },

  // ============================================================================
  // TREND (7)
  // ============================================================================
  'Cumulative Return': {
    id: 'Cumulative Return',
    name: 'Cumulative Return',
    category: 'trend',
    defaultPeriod: 252,
    minPeriod: 20,
    maxPeriod: 1260,
    comparatorHint: 'GT',
    thresholdRange: [-50, 200],
    description: 'Total return over period',
  },
  'SMA of Returns': {
    id: 'SMA of Returns',
    name: 'SMA of Returns',
    category: 'trend',
    defaultPeriod: 20,
    minPeriod: 2,
    maxPeriod: 252,
    comparatorHint: 'GT',
    thresholdRange: [-5, 5],
    description: 'Moving average of returns',
  },
  'Trend Clarity': {
    id: 'Trend Clarity',
    name: 'Trend Clarity (R² of linear regression)',
    category: 'trend',
    defaultPeriod: 60,
    minPeriod: 10,
    maxPeriod: 252,
    comparatorHint: 'GT',
    thresholdRange: [0, 1],
    description: 'R-squared of linear regression',
  },
  'Ultimate Smoother': {
    id: 'Ultimate Smoother',
    name: 'Ultimate Smoother (Ehlers filter)',
    category: 'trend',
    defaultPeriod: 5,
    minPeriod: 2,
    maxPeriod: 20,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Ehlers Ultimate Smoother',
  },
  'Linear Reg Slope': {
    id: 'Linear Reg Slope',
    name: 'Linear Regression Slope',
    category: 'trend',
    defaultPeriod: 20,
    minPeriod: 5,
    maxPeriod: 252,
    comparatorHint: 'GT',
    thresholdRange: [-10, 10],
    description: 'Slope of linear regression',
  },
  'Linear Reg Value': {
    id: 'Linear Reg Value',
    name: 'Linear Regression Value',
    category: 'trend',
    defaultPeriod: 20,
    minPeriod: 5,
    maxPeriod: 252,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Linear regression forecast',
  },
  'Price vs SMA': {
    id: 'Price vs SMA',
    name: 'Price vs SMA',
    category: 'trend',
    defaultPeriod: 50,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Price divided by SMA',
  },

  // ============================================================================
  // AROON (3)
  // ============================================================================
  'Aroon Up': {
    id: 'Aroon Up',
    name: 'Aroon Up',
    category: 'aroon',
    defaultPeriod: 25,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'GT',
    thresholdRange: [0, 100],
    description: 'Aroon Up indicator',
  },
  'Aroon Down': {
    id: 'Aroon Down',
    name: 'Aroon Down',
    category: 'aroon',
    defaultPeriod: 25,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'LT',
    thresholdRange: [0, 100],
    description: 'Aroon Down indicator',
  },
  'Aroon Oscillator': {
    id: 'Aroon Oscillator',
    name: 'Aroon Oscillator',
    category: 'aroon',
    defaultPeriod: 25,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [-100, 100],
    description: 'Aroon Up - Aroon Down',
  },

  // ============================================================================
  // MACD/PPO (2)
  // ============================================================================
  'MACD Histogram': {
    id: 'MACD Histogram',
    name: 'MACD Histogram',
    category: 'macd_ppo',
    defaultPeriod: 1,
    minPeriod: 1,
    maxPeriod: 1,
    comparatorHint: 'BOTH',
    thresholdRange: [-5, 5],
    description: 'MACD line minus signal line',
    windowless: true,
  },
  'PPO Histogram': {
    id: 'PPO Histogram',
    name: 'PPO Histogram',
    category: 'macd_ppo',
    defaultPeriod: 1,
    minPeriod: 1,
    maxPeriod: 1,
    comparatorHint: 'BOTH',
    thresholdRange: [-10, 10],
    description: 'Percentage Price Oscillator histogram',
    windowless: true,
  },

  // ============================================================================
  // VOLUME (3)
  // ============================================================================
  'Money Flow Index': {
    id: 'Money Flow Index',
    name: 'Money Flow Index (MFI)',
    category: 'volume',
    defaultPeriod: 14,
    minPeriod: 2,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0, 100],
    description: 'Volume-weighted RSI',
  },
  'OBV Rate of Change': {
    id: 'OBV Rate of Change',
    name: 'OBV Rate of Change',
    category: 'volume',
    defaultPeriod: 10,
    minPeriod: 1,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [-50, 50],
    description: 'On-Balance Volume ROC',
  },
  'VWAP Ratio': {
    id: 'VWAP Ratio',
    name: 'VWAP Ratio',
    category: 'volume',
    defaultPeriod: 20,
    minPeriod: 1,
    maxPeriod: 200,
    comparatorHint: 'BOTH',
    thresholdRange: [0.8, 1.2],
    description: 'Price / VWAP ratio',
  },
};

// Helper functions
export const getIndicatorsByCategory = () => {
  const categories: Record<string, IndicatorDefinition[]> = {};

  Object.values(INDICATORS).forEach(indicator => {
    if (!categories[indicator.category]) {
      categories[indicator.category] = [];
    }
    categories[indicator.category].push(indicator);
  });

  return categories;
};

export const getCategoryName = (category: string): string => {
  const names: Record<string, string> = {
    price: 'Price',
    moving_average: 'Moving Averages',
    rsi: 'RSI & Variants',
    momentum: 'Momentum',
    volatility: 'Volatility',
    trend: 'Trend',
    aroon: 'Aroon',
    macd_ppo: 'MACD/PPO',
    volume: 'Volume',
  };
  return names[category] || category;
};

export const INDICATOR_CATEGORIES = [
  'price',
  'moving_average',
  'rsi',
  'momentum',
  'volatility',
  'trend',
  'aroon',
  'macd_ppo',
  'volume',
] as const;
